<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DentalClinic.MODEL\DentalClinic.MODEL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Patient\" />
    <Folder Include="Receptionist\" />
  </ItemGroup>

</Project>
